# Site settings
title: Romain Butteaud
url: "http://romainbutteaud.com"

contact:
  email: contact@romainbutteaud.com
  github: romainbutteaud
  facebook: romainbutteaud
  instagram: romainbutteaud
  linkedin: romainbutteaud
  stackoverflow: 1861084
  twitter: romainbutteaud

# Build settings
markdown: kramdown

collections:
  projects:
    output: true

