# Site settings
title: Romain Butteaud
email: contact@romainbutteaud.com
description: Write an awesome description...
url: "http://romainbutteaud.com"
github_username: romainbutteaud

# Build settings
markdown: kramdown

collections:
  projects:
    output: true